// import styles from "../styles/Home.module.css";
import Head from "next/head";
import { app } from "../../firebaseConfig";
import { useEffect } from "react";
import {
  getAuth,
  signInWithEmailAndPassword,
  GoogleAuthProvider,
  GithubAuthProvider,
  signInWithPopup,
} from "firebase/auth";
import { useState } from "react";
import { useRouter } from "next/router";
export default function Register() {
  const auth = getAuth();
  const googleProvider = new GoogleAuthProvider();
  const githubProvider = new GithubAuthProvider();
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const signUp = () => {
    signInWithEmailAndPassword(auth, email, password)
      .then((response) => {
        console.log(response.user);
        sessionStorage.setItem("Token", response.user.accessToken);
        router.push("/admin-dashboard");
      })
      .catch((err) => {
        alert("Cannot Log in");
        router.push("/register");
      });
  };

  const signUpWithGoogle = () => {
    signInWithPopup(auth, googleProvider).then((response) => {
      sessionStorage.setItem("Token", response.user.accessToken);
      console.log(response.user);
      router.push("/admin-dashboard");
    });
  };

  const signUpWithGithub = () => {
    signInWithPopup(auth, githubProvider).then((response) => {
      sessionStorage.setItem("Token", response.user.accessToken);
      console.log(response.user);
      router.push("/admin-dashboard");
    });
  };

  useEffect(() => {
    let token = sessionStorage.getItem("Token");

    if (token) {
      router.push("/admin-dashboard");
    }
  }, []);

  return (
    <div className="">
      <Head>
        <title>Pricesure Admin login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1>Login</h1>

        <input
          placeholder="Email"
          className=""
          onChange={(event) => setEmail(event.target.value)}
          value={email}
          type="email"
        />
        <input
          placeholder="Password"
          className=""
          onChange={(event) => setPassword(event.target.value)}
          value={password}
          type="password"
        />

        <button className="" onClick={signUp}>
          Sign In
        </button>
        <hr />
        <button className="" onClick={signUpWithGoogle}>
          Sign Up with Google
        </button>
        <hr />
        <button onClick={signUpWithGithub} className="">
          Sign Up with Github
        </button>
      </main>
    </div>
  );
}
